---
packages:
  - jq
  - nmap
  - dhcpcd
  - avahi
  - dbus
  - node_exporter
  - tor

sysctl:
  - { name: "net.inet.ip.forwarding", value: 1 }
  - { name: "net.inet6.ip6.forwarding", value: 1 }
  - { name: "net.inet.ip.mforwarding", value: 1 }
  - { name: "net.inet6.ip6.mforwarding", value: 1 }

dns_servers:
  # the hostname after "#" is not a comment, it is used for TLS checks:
  - "2606:4700:4700::1111@853#cloudflare-dns.com"
  - "1.1.1.1@853#cloudflare-dns.com"
  - "2606:4700:4700::1001@853#cloudflare-dns.com"
  - "1.0.0.1@853#cloudflare-dns.com"

# desired uplink bandwidth for FQ-CoDel in pf
uplink_bandwidth: 30M

wan:
  interface: rge0
lan:
  net: 192.168.0.0
  address: 192.168.0.1
  mask: 255.255.252.0
  dhcp_start: 192.168.0.150
  dhcp_end: 192.168.0.200
  interface: vport0
  bridge: veb0
  interfaces:
    - rge1
    - rge2
    - rge3
    - rge4
    - rge5

  hosts:
    ### Wired block
    # server
    192.168.0.10:
      hostname: sokoban
      mac: 2c:fd:a1:ba:38:aa
    # desktop
    192.168.0.11:
      hostname: abacus
      mac: 3c:7c:3f:2f:71:3a
    # new desktop
    192.168.0.12:
      hostname: beast
      mac: c8:7f:54:67:ef:e4

    192.168.0.13:
      hostname: homeassistant
      mac: fe:e1:bb:d1:a8:71
      ports:
        tcp:
          - 8123

    # work laptop
    192.168.0.15:
      hostname: work
      mac: d8:f2:ca:b4:00:14

    # new work laptop
    192.168.0.16:
      hostname: lenovo
      mac: 04:7b:cb:bb:1c:b0

    # work laptop ethernet
    192.168.0.17:
      hostname: lenovoeth
      mac: e8:80:88:8b:fc:1d

    # personal laptop, lenovo A485
    192.168.0.18:
      hostname: wololo
      mac: 8c:16:45:d8:8e:ef

    ### Wireless block

    # personal phone
    192.168.0.20:
      hostname: pixel6a
      mac: c8:2a:dd:9a:f0:21

    # old laptop
    192.168.0.30:
      hostname: omicron
      mac: 3c:97:0e:26:6b:74

    # t431s
    192.168.0.31:
      hostname: tetris
      mac: 3c:97:0e:ad:47:12

    # personal laptop wifi, lenovo A485
    192.168.0.32:
      hostname: wololo
      mac: f8:ac:65:fb:39:fc

    # eero
    192.168.0.40:
      hostname: eero1
      mac: 6c:ae:f6:a0:6e:12
    192.168.0.41:
      hostname: eero2
      mac: 3c:5c:f1:02:2d:ad

    192.168.0.42:
      hostname: eero-gw
      mac: 64:97:14:01:43:f2

    # smart garbage

    # Alloy Smart Hub
    192.168.0.50:
      mac: e8:ca:c8:15:23:76
      hostname: alloy

    # ESP32 bluetooth proxy
    192.168.0.51:
      mac: 30:c6:f7:15:13:a4
      hostname: bluetooth-proxy

    # ESP32 server-reset switch
    192.168.0.52:
      mac: 30:c6:f7:14:f2:90
      hostname: server-reset

    # kubernetes ingress
    192.168.3.10:
      hostname: kube-ingress
      ports:
        tcp:
          - 80
          - 443

# ports example:
#   192.168.99.99:
#     hostname: blah
#     mac: fe:fi:fo:fu:fa:fo
#     ports:
#       tcp:
#         - 80
#         - 443
#       udp:
#         - 53

