---
packages:
  - jq
  - nmap
  - dhcpcd
  - avahi
  - dbus
  - node_exporter

sysctl:
  - { name: "net.inet.ip.forwarding", value: 1 }
  - { name: "net.inet6.ip6.forwarding", value: 1 }
  - { name: "net.inet.ip.mforwarding", value: 1 }
  - { name: "net.inet6.ip6.mforwarding", value: 1 }

dns_servers:
  - 8.8.8.8
  - 8.8.4.4

# desired uplink bandwidth for FQ-CoDel in pf
uplink_bandwidth: 30M

wan:
  interface: rge0
lan:
  net: 192.168.0.0
  address: 192.168.0.1
  mask: 255.255.252.0
  dhcp_start: 192.168.0.50
  dhcp_end: 192.168.0.100
  interface: vport0
  bridge: veb0
  interfaces:
    - rge1
    - rge2
    - rge3
    - rge4
    - rge5

  hosts:
    # server
    192.168.0.10:
      hostname: sokoban
      mac: 2c:fd:a1:ba:38:aa
    # desktop
    192.168.0.11:
      hostname: abacus
      mac: 3c:7c:3f:2f:71:3a
    # work laptop
    192.168.0.15:
      hostname: work
      mac: d8:f2:ca:b4:00:14

    # personal laptop
    192.168.0.32:
      hostname: wololo
      mac: 2e:6d:f3:32:a6:32

    # t431s
    192.168.0.31:
      hostname: tetris
      mac: 3c:97:0e:ad:47:12

    # old laptop
    192.168.0.30:
      hostname: omicron
      mac: 3c:97:0e:26:6b:74

    # eero
    192.168.0.40:
      hostname: eero1
      mac: 6c:ae:f6:a0:6e:12
    192.168.0.41:
      hostname: eero2
      mac: 3c:5c:f1:02:2d:ad

    # kubernetes ingress
    192.168.3.10:
      hostname: kube-ingress
      ports:
        tcp:
          - 80
          - 443

# ports example:
#   192.168.99.99:
#     hostname: blah
#     mac: fe:fi:fo:fu:fa:fo
#     ports:
#       tcp:
#         - 80
#         - 443
#       udp:
#         - 53

