- name: dhcpcd
  service:
    name: dhcpcd
    state: started
    enabled: true

- name: dhcpd
  service:
    name: dhcpd
    state: restarted
    enabled: true

- name: rad
  service:
    name: rad
    state: started
    enabled: true

- name: unbound
  service:
    name: unbound
    state: restarted
    enabled: true

- name: ntpd
  service:
    name: ntpd
    state: restarted
    enabled: true

- name: netstart
  command: sh /etc/netstart

- name: pf
  command: pfctl -f /etc/pf.conf

- name: smtpd
  service:
    name: smtpd
    state: restarted
    enabled: true

- name: tor
  service:
    name: tor
    state: restarted
    enabled: true

