---

- name: install packages
  package:
    name: "{{ item }}"
    state: installed
  loop: "{{ packages }}"

- name: enable some daemons
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop: 
    - messagebus
    - avahi_daemon
    - node_exporter

- name: Set sysctl options
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    reload: yes
  loop: "{{ sysctl }}"

- name: setup lan interface
  template:
    src: hostname.vport.j2
    dest: /etc/hostname.{{ lan.interface }}
    mode: 0640
    owner: root
    group: wheel
  notify: netstart

- name: up lan nics
  template:
    src: hostname.lan.j2
    dest: /etc/hostname.{{ item }}
    mode: 0640
    owner: root
    group: wheel
  loop: "{{ lan.interfaces }}"
  notify: netstart

- name: setup bridge
  template:
    src: hostname.veb.j2
    dest: /etc/hostname.{{ lan.bridge }}
    mode: 0640
    owner: root
    group: wheel
  notify: netstart

# this also triggers dhcpv4 on wan
- name: setup wan interface
  template:
    src: hostname.wan.j2
    dest: /etc/hostname.{{ wan.interface }}
    mode: 0640
    owner: root
    group: wheel
  notify: netstart

- name: setup wan dhcpv6
  template:
    src: dhcpcd.conf.j2
    dest: /etc/dhcpcd.conf
    mode: 0640
    owner: root
    group: wheel
  notify: dhcpcd

- name: setup rad
  template:
    src: rad.conf.j2
    dest: /etc/rad.conf
    mode: 0640
    owner: root
    group: wheel
  notify: rad

- name: setup pf
  template:
    src: pf.conf.j2
    dest: /etc/pf.conf
    mode: 0600
    owner: root
    group: wheel
    validate: pfctl -n -f %s
  notify: pf

- name: setup ntpd
  template:
    src: ntpd.conf.j2
    dest: /etc/ntpd.conf
    mode: 0640
    owner: root
    group: wheel
    validate: ntpd -n -f %s
  notify: ntpd

- name: setup dhcpd
  template:
    src: dhcpd.conf.j2
    dest: /etc/dhcpd.conf
    mode: 0640
    owner: root
    group: wheel
    validate: dhcpd -n -c %s
  notify: dhcpd

- name: setup unbound
  template:
    src: unbound.conf.j2
    dest: /var/unbound/etc/unbound.conf
    mode: 0640
    owner: root
    group: _unbound
    validate: unbound -v -c %s
  notify: unbound

- name: setup smtpd secrets
  template:
    src: smtpd-secrets.j2
    dest: /etc/mail/secrets
    mode: 0640
    owner: root
    group: wheel
 
- name: setup smtpd
  template:
    src: smtpd.conf.j2
    dest: /etc/mail/smtpd.conf
    mode: 0640
    owner: root
    group: wheel
    validate: smtpd -n -f %s
  notify: smtpd

